/* localization.js — Grid Rogue v0.1.8
   I18N separado (window.I18n)
   ✅ Añade: zh (简体), zh-Hant (繁體), ja, ko, ru, ar + extra (tr, pl, nl)
   ✅ Normalización mejorada (zh-Hans/zh-Hant, regiones, _ vs -)
   ✅ Soporte RTL (ar): ajusta document.documentElement.dir
*/
(() => {
  "use strict";

  const RTL_LANGS = new Set(["ar"]);

  const normalize = (raw) => {
    let s = String(raw || "").toLowerCase().trim();
    if (!s || s === "auto") return "auto";

    // unify separators
    s = s.replace(/_/g, "-");

    // Chinese variants
    // - zh-hant / zh-tw / zh-hk / zh-mo => Traditional
    // - default => Simplified
    if (s === "zh" || s.startsWith("zh-")) {
      const hasHant = s.includes("hant");
      const isTW = s.includes("-tw");
      const isHK = s.includes("-hk");
      const isMO = s.includes("-mo");
      if (hasHant || isTW || isHK || isMO) return "zh-hant";
      return "zh";
    }

    const base = s.split("-")[0];

    // keep existing special-cases
    if (base === "pt") return "pt";
    if (base === "ca") return "ca";

    // general
    return base;
  };

  const dict = {
    es: {
      langName: "Español",
      defaultPlayer: "Jugador",
      app_ready: "Listo",
      app_loading: "Iniciando…",
      app_pwa: "PWA…",
      audio_ok: "Audio OK",
      update_apply_end: "Update listo: se aplicará al terminar.",
      update_available: "Actualización disponible.",
      update_apply_end_short: "Se aplicará al terminar.",
      pill_update: "Actualizar",
      toast_trap: "Trampa",
      toast_combo_mult: "Combo: +MULT",
      toast_upgrade: "Mejora: {0}",
      toast_reroll: "Reroll",
      toast_skip: "Saltar",
      toast_shield_saved: "El escudo salvó un KO",
      name_min: "Nombre mínimo 2 letras",
      combo_hint: "Completa la secuencia para subir multiplicador.",
      stats_reason: "Motivo",
      stats_level: "Nivel",
      stats_time: "Tiempo",
      stats_streak: "Racha",
      stats_mult: "Mult",
      cell_coin: "Coin",
      cell_gem: "Gem",
      cell_bonus: "Bonus",
      opt_language: "Idioma",
      lang_auto: "Auto",
      up_choose: "Elige una mejora",
      up_level_title: "Nivel {0}",
      rarity_common: "Común",
      rarity_rare: "Rara",
      rarity_epic: "Épica",
      rarity_legendary: "Legendaria",
      new_profile: "Crear nuevo…",
      confirm_clear_local: "¿Borrar datos locales? (Perfiles, ajustes, runs)",
      tag_defense: "Defensa",
      tag_qol: "QoL",
      tag_points: "Puntos",
      tag_mobility: "Movilidad",
      tag_upgrades: "Upgrades",
      tag_combo: "Combo",
      up_shield_name: "Escudo",
      up_shield_desc: "Bloquea 1 KO (se consume).",
      up_mag1_name: "Imán I",
      up_mag1_desc: "Atrae premios cercanos (radio 1).",
      up_mag2_name: "Imán II",
      up_mag2_desc: "Imán mejorado (radio 2).",
      up_mag3_name: "Imán III",
      up_mag3_desc: "Radio 3 (máximo).",
      up_boost_name: "Puntos +",
      up_boost_desc: "Más puntos (+8%).",
      up_trap_name: "Resistencia a trampas",
      up_trap_desc: "Reduce penalización de trampas.",
      up_zone_name: "Zona +",
      up_zone_desc: "Zona de movimiento más alta (+1 fila).",
      up_coin_name: "Coin +",
      up_coin_desc: "Coin vale más (+2).",
      up_gem_name: "Gem +",
      up_gem_desc: "Gem vale más (+6).",
      up_bonus_name: "Bonus +",
      up_bonus_desc: "Bonus vale más (+10).",
      up_reroll_name: "Reroll +",
      up_reroll_desc: "Ganas 1 reroll extra.",
      up_mult_name: "Mult +",
      up_mult_desc: "Sube multiplicador base (+0.10).",
    },

    en: {
      langName: "English",
      defaultPlayer: "Player",
      app_ready: "Ready",
      app_loading: "Starting…",
      app_pwa: "PWA…",
      audio_ok: "Audio OK",
      update_apply_end: "Update ready: it will apply after the run.",
      update_available: "Update available.",
      update_apply_end_short: "It will apply after the run.",
      pill_update: "Update",
      toast_trap: "Trap",
      toast_combo_mult: "Combo: +MULT",
      toast_upgrade: "Upgrade: {0}",
      toast_reroll: "Reroll",
      toast_skip: "Skip",
      toast_shield_saved: "Shield saved you from a KO",
      name_min: "Name must be at least 2 characters",
      combo_hint: "Complete the sequence to increase multiplier.",
      stats_reason: "Reason",
      stats_level: "Level",
      stats_time: "Time",
      stats_streak: "Streak",
      stats_mult: "Mult",
      cell_coin: "Coin",
      cell_gem: "Gem",
      cell_bonus: "Bonus",
      opt_language: "Language",
      lang_auto: "Auto",
      up_choose: "Choose an upgrade",
      up_level_title: "Level {0}",
      rarity_common: "Common",
      rarity_rare: "Rare",
      rarity_epic: "Epic",
      rarity_legendary: "Legendary",
      new_profile: "Create new…",
      confirm_clear_local: "Clear local data? (Profiles, settings, runs)",
      tag_defense: "Defense",
      tag_qol: "QoL",
      tag_points: "Points",
      tag_mobility: "Mobility",
      tag_upgrades: "Upgrades",
      tag_combo: "Combo",
      up_shield_name: "Shield",
      up_shield_desc: "Blocks 1 KO (consumed).",
      up_mag1_name: "Magnet I",
      up_mag1_desc: "Pulls nearby rewards (radius 1).",
      up_mag2_name: "Magnet II",
      up_mag2_desc: "Improved magnet (radius 2).",
      up_mag3_name: "Magnet III",
      up_mag3_desc: "Radius 3 (max).",
      up_boost_name: "Score +",
      up_boost_desc: "More points (+8%).",
      up_trap_name: "Trap resistance",
      up_trap_desc: "Reduces trap penalty.",
      up_zone_name: "Zone +",
      up_zone_desc: "Taller movement zone (+1 row).",
      up_coin_name: "Coin +",
      up_coin_desc: "Coin worth more (+2).",
      up_gem_name: "Gem +",
      up_gem_desc: "Gem worth more (+6).",
      up_bonus_name: "Bonus +",
      up_bonus_desc: "Bonus worth more (+10).",
      up_reroll_name: "Reroll +",
      up_reroll_desc: "Gain 1 extra reroll.",
      up_mult_name: "Mult +",
      up_mult_desc: "Increase base multiplier (+0.10).",
    },

    fr: {
      langName: "Français",
      defaultPlayer: "Joueur",
      app_ready: "Prêt",
      app_loading: "Démarrage…",
      app_pwa: "PWA…",
      audio_ok: "Audio OK",
      update_apply_end: "MAJ prête : elle s’appliquera après la partie.",
      update_available: "Mise à jour disponible.",
      update_apply_end_short: "Après la partie.",
      pill_update: "Mettre à jour",
      toast_trap: "Piège",
      toast_combo_mult: "Combo : +MULT",
      toast_upgrade: "Amélioration : {0}",
      toast_reroll: "Relance",
      toast_skip: "Passer",
      toast_shield_saved: "Bouclier : KO évité",
      name_min: "Nom : minimum 2 caractères",
      combo_hint: "Complète la séquence pour augmenter le multiplicateur.",
      stats_reason: "Raison",
      stats_level: "Niveau",
      stats_time: "Temps",
      stats_streak: "Série",
      stats_mult: "Mult",
      cell_coin: "Pièce",
      cell_gem: "Gemme",
      cell_bonus: "Bonus",
      opt_language: "Langue",
      lang_auto: "Auto",
      up_choose: "Choisis une amélioration",
      up_level_title: "Niveau {0}",
      rarity_common: "Commune",
      rarity_rare: "Rare",
      rarity_epic: "Épique",
      rarity_legendary: "Légendaire",
      new_profile: "Créer nouveau…",
      confirm_clear_local: "Effacer les données locales ? (Profils, réglages, runs)",
      tag_defense: "Défense",
      tag_qol: "QoL",
      tag_points: "Points",
      tag_mobility: "Mobilité",
      tag_upgrades: "Amélios",
      tag_combo: "Combo",
      up_shield_name: "Bouclier",
      up_shield_desc: "Bloque 1 KO (consommé).",
      up_mag1_name: "Aimant I",
      up_mag1_desc: "Attire les récompenses (rayon 1).",
      up_mag2_name: "Aimant II",
      up_mag2_desc: "Aimant amélioré (rayon 2).",
      up_mag3_name: "Aimant III",
      up_mag3_desc: "Rayon 3 (max).",
      up_boost_name: "Score +",
      up_boost_desc: "Plus de points (+8%).",
      up_trap_name: "Résistance pièges",
      up_trap_desc: "Réduit la pénalité des pièges.",
      up_zone_name: "Zone +",
      up_zone_desc: "Zone de mouvement plus haute (+1 ligne).",
      up_coin_name: "Pièce +",
      up_coin_desc: "Pièce vaut plus (+2).",
      up_gem_name: "Gemme +",
      up_gem_desc: "Gemme vaut plus (+6).",
      up_bonus_name: "Bonus +",
      up_bonus_desc: "Bonus vaut plus (+10).",
      up_reroll_name: "Relance +",
      up_reroll_desc: "Gagne 1 relance.",
      up_mult_name: "Mult +",
      up_mult_desc: "Augmente le mult de base (+0,10).",
    },

    de: {
      langName: "Deutsch",
      defaultPlayer: "Spieler",
      app_ready: "Bereit",
      app_loading: "Startet…",
      app_pwa: "PWA…",
      audio_ok: "Audio OK",
      update_apply_end: "Update bereit: wird nach dem Lauf angewendet.",
      update_available: "Update verfügbar.",
      update_apply_end_short: "Nach dem Lauf.",
      pill_update: "Aktualisieren",
      toast_trap: "Falle",
      toast_combo_mult: "Combo: +MULT",
      toast_upgrade: "Upgrade: {0}",
      toast_reroll: "Neu würfeln",
      toast_skip: "Überspringen",
      toast_shield_saved: "Schild hat dich vor KO gerettet",
      name_min: "Name: mindestens 2 Zeichen",
      combo_hint: "Vervollständige die Sequenz für mehr Multiplikator.",
      stats_reason: "Grund",
      stats_level: "Level",
      stats_time: "Zeit",
      stats_streak: "Serie",
      stats_mult: "Mult",
      cell_coin: "Coin",
      cell_gem: "Gem",
      cell_bonus: "Bonus",
      opt_language: "Sprache",
      lang_auto: "Auto",
      up_choose: "Wähle ein Upgrade",
      up_level_title: "Level {0}",
      rarity_common: "Gewöhnlich",
      rarity_rare: "Selten",
      rarity_epic: "Episch",
      rarity_legendary: "Legendär",
      new_profile: "Neu erstellen…",
      confirm_clear_local: "Lokale Daten löschen? (Profile, Einstellungen, Runs)",
      tag_defense: "Verteidigung",
      tag_qol: "QoL",
      tag_points: "Punkte",
      tag_mobility: "Mobilität",
      tag_upgrades: "Upgrades",
      tag_combo: "Combo",
      up_shield_name: "Schild",
      up_shield_desc: "Blockt 1 KO (verbraucht).",
      up_mag1_name: "Magnet I",
      up_mag1_desc: "Zieht Belohnungen an (Radius 1).",
      up_mag2_name: "Magnet II",
      up_mag2_desc: "Besserer Magnet (Radius 2).",
      up_mag3_name: "Magnet III",
      up_mag3_desc: "Radius 3 (Max).",
      up_boost_name: "Score +",
      up_boost_desc: "Mehr Punkte (+8%).",
      up_trap_name: "Fallenresistenz",
      up_trap_desc: "Reduziert Fallenstrafe.",
      up_zone_name: "Zone +",
      up_zone_desc: "Höhere Bewegungszone (+1 Reihe).",
      up_coin_name: "Coin +",
      up_coin_desc: "Coin ist mehr wert (+2).",
      up_gem_name: "Gem +",
      up_gem_desc: "Gem ist mehr wert (+6).",
      up_bonus_name: "Bonus +",
      up_bonus_desc: "Bonus ist mehr wert (+10).",
      up_reroll_name: "Reroll +",
      up_reroll_desc: "Erhalte 1 zusätzlichen Reroll.",
      up_mult_name: "Mult +",
      up_mult_desc: "Erhöht Basismultiplikator (+0,10).",
    },

    it: {
      langName: "Italiano",
      defaultPlayer: "Giocatore",
      app_ready: "Pronto",
      app_loading: "Avvio…",
      app_pwa: "PWA…",
      audio_ok: "Audio OK",
      update_apply_end: "Aggiornamento pronto: si applicherà dopo la run.",
      update_available: "Aggiornamento disponibile.",
      update_apply_end_short: "Dopo la run.",
      pill_update: "Aggiorna",
      toast_trap: "Trappola",
      toast_combo_mult: "Combo: +MULT",
      toast_upgrade: "Miglioria: {0}",
      toast_reroll: "Reroll",
      toast_skip: "Salta",
      toast_shield_saved: "Scudo: KO evitato",
      name_min: "Nome: minimo 2 caratteri",
      combo_hint: "Completa la sequenza per aumentare il moltiplicatore.",
      stats_reason: "Motivo",
      stats_level: "Livello",
      stats_time: "Tempo",
      stats_streak: "Serie",
      stats_mult: "Mult",
      cell_coin: "Coin",
      cell_gem: "Gem",
      cell_bonus: "Bonus",
      opt_language: "Lingua",
      lang_auto: "Auto",
      up_choose: "Scegli un upgrade",
      up_level_title: "Livello {0}",
      rarity_common: "Comune",
      rarity_rare: "Raro",
      rarity_epic: "Epico",
      rarity_legendary: "Leggendario",
      new_profile: "Crea nuovo…",
      confirm_clear_local: "Cancellare i dati locali? (Profili, impostazioni, runs)",
      tag_defense: "Difesa",
      tag_qol: "QoL",
      tag_points: "Punti",
      tag_mobility: "Mobilità",
      tag_upgrades: "Upgrade",
      tag_combo: "Combo",
      up_shield_name: "Scudo",
      up_shield_desc: "Blocca 1 KO (consumato).",
      up_mag1_name: "Magnete I",
      up_mag1_desc: "Attira ricompense (raggio 1).",
      up_mag2_name: "Magnete II",
      up_mag2_desc: "Magnete migliorato (raggio 2).",
      up_mag3_name: "Magnete III",
      up_mag3_desc: "Raggio 3 (max).",
      up_boost_name: "Punti +",
      up_boost_desc: "Più punti (+8%).",
      up_trap_name: "Resistenza trappole",
      up_trap_desc: "Riduce la penalità delle trappole.",
      up_zone_name: "Zona +",
      up_zone_desc: "Zona movimento più alta (+1 riga).",
      up_coin_name: "Coin +",
      up_coin_desc: "Coin vale di più (+2).",
      up_gem_name: "Gem +",
      up_gem_desc: "Gem vale di più (+6).",
      up_bonus_name: "Bonus +",
      up_bonus_desc: "Bonus vale di più (+10).",
      up_reroll_name: "Reroll +",
      up_reroll_desc: "Ottieni 1 reroll extra.",
      up_mult_name: "Mult +",
      up_mult_desc: "Aumenta mult base (+0,10).",
    },

    pt: {
      langName: "Português",
      defaultPlayer: "Jogador",
      app_ready: "Pronto",
      app_loading: "A iniciar…",
      app_pwa: "PWA…",
      audio_ok: "Áudio OK",
      update_apply_end: "Update pronto: aplica-se no fim da run.",
      update_available: "Atualização disponível.",
      update_apply_end_short: "No fim da run.",
      pill_update: "Atualizar",
      toast_trap: "Armadilha",
      toast_combo_mult: "Combo: +MULT",
      toast_upgrade: "Upgrade: {0}",
      toast_reroll: "Reroll",
      toast_skip: "Saltar",
      toast_shield_saved: "Escudo salvou-te de um KO",
      name_min: "Nome: mínimo 2 caracteres",
      combo_hint: "Completa a sequência para aumentar o multiplicador.",
      stats_reason: "Motivo",
      stats_level: "Nível",
      stats_time: "Tempo",
      stats_streak: "Sequência",
      stats_mult: "Mult",
      cell_coin: "Coin",
      cell_gem: "Gem",
      cell_bonus: "Bónus",
      opt_language: "Idioma",
      lang_auto: "Auto",
      up_choose: "Escolhe um upgrade",
      up_level_title: "Nível {0}",
      rarity_common: "Comum",
      rarity_rare: "Raro",
      rarity_epic: "Épico",
      rarity_legendary: "Lendário",
      new_profile: "Criar novo…",
      confirm_clear_local: "Apagar dados locais? (Perfis, definições, runs)",
      tag_defense: "Defesa",
      tag_qol: "QoL",
      tag_points: "Pontos",
      tag_mobility: "Mobilidade",
      tag_upgrades: "Upgrades",
      tag_combo: "Combo",
      up_shield_name: "Escudo",
      up_shield_desc: "Bloqueia 1 KO (consome).",
      up_mag1_name: "Íman I",
      up_mag1_desc: "Atrai prémios (raio 1).",
      up_mag2_name: "Íman II",
      up_mag2_desc: "Íman melhorado (raio 2).",
      up_mag3_name: "Íman III",
      up_mag3_desc: "Raio 3 (máx).",
      up_boost_name: "Pontos +",
      up_boost_desc: "Mais pontos (+8%).",
      up_trap_name: "Resistência a armadilhas",
      up_trap_desc: "Reduz penalização das armadilhas.",
      up_zone_name: "Zona +",
      up_zone_desc: "Zona de movimento maior (+1 linha).",
      up_coin_name: "Coin +",
      up_coin_desc: "Coin vale mais (+2).",
      up_gem_name: "Gem +",
      up_gem_desc: "Gem vale mais (+6).",
      up_bonus_name: "Bónus +",
      up_bonus_desc: "Bónus vale mais (+10).",
      up_reroll_name: "Reroll +",
      up_reroll_desc: "Ganhas 1 reroll extra.",
      up_mult_name: "Mult +",
      up_mult_desc: "Aumenta mult base (+0,10).",
    },

    ca: {
      langName: "Català",
      defaultPlayer: "Jugador",
      app_ready: "A punt",
      app_loading: "Iniciant…",
      app_pwa: "PWA…",
      audio_ok: "Àudio OK",
      update_apply_end: "Actualització llesta: s’aplicarà en acabar la run.",
      update_available: "Actualització disponible.",
      update_apply_end_short: "En acabar la run.",
      pill_update: "Actualitza",
      toast_trap: "Trampa",
      toast_combo_mult: "Combo: +MULT",
      toast_upgrade: "Millora: {0}",
      toast_reroll: "Reroll",
      toast_skip: "Saltar",
      toast_shield_saved: "L’escut t’ha salvat d’un KO",
      name_min: "Nom: mínim 2 lletres",
      combo_hint: "Completa la seqüència per pujar multiplicador.",
      stats_reason: "Motiu",
      stats_level: "Nivell",
      stats_time: "Temps",
      stats_streak: "Ratxa",
      stats_mult: "Mult",
      cell_coin: "Coin",
      cell_gem: "Gem",
      cell_bonus: "Bonus",
      opt_language: "Idioma",
      lang_auto: "Auto",
      up_choose: "Tria una millora",
      up_level_title: "Nivell {0}",
      rarity_common: "Comuna",
      rarity_rare: "Rara",
      rarity_epic: "Èpica",
      rarity_legendary: "Legendària",
      new_profile: "Crear nou…",
      confirm_clear_local: "Esborrar dades locals? (Perfils, opcions, runs)",
      tag_defense: "Defensa",
      tag_qol: "QoL",
      tag_points: "Punts",
      tag_mobility: "Mobilitat",
      tag_upgrades: "Upgrades",
      tag_combo: "Combo",
      up_shield_name: "Escut",
      up_shield_desc: "Bloqueja 1 KO (es consumeix).",
      up_mag1_name: "Imant I",
      up_mag1_desc: "Atrau premis (radi 1).",
      up_mag2_name: "Imant II",
      up_mag2_desc: "Imant millorat (radi 2).",
      up_mag3_name: "Imant III",
      up_mag3_desc: "Radi 3 (màxim).",
      up_boost_name: "Punts +",
      up_boost_desc: "Més punts (+8%).",
      up_trap_name: "Resistència trampes",
      up_trap_desc: "Redueix penalització de trampes.",
      up_zone_name: "Zona +",
      up_zone_desc: "Zona de moviment més alta (+1 fila).",
      up_coin_name: "Coin +",
      up_coin_desc: "Coin val més (+2).",
      up_gem_name: "Gem +",
      up_gem_desc: "Gem val més (+6).",
      up_bonus_name: "Bonus +",
      up_bonus_desc: "Bonus val més (+10).",
      up_reroll_name: "Reroll +",
      up_reroll_desc: "Guanyes 1 reroll extra.",
      up_mult_name: "Mult +",
      up_mult_desc: "Puja mult base (+0,10).",
    },

    // ───────────────────────── NUEVOS ─────────────────────────

    zh: {
      langName: "中文（简体）",
      defaultPlayer: "玩家",
      app_ready: "就绪",
      app_loading: "启动中…",
      app_pwa: "PWA…",
      audio_ok: "音频 OK",
      update_apply_end: "更新已就绪：将在本局结束后应用。",
      update_available: "有可用更新。",
      update_apply_end_short: "本局结束后应用。",
      pill_update: "更新",
      toast_trap: "陷阱",
      toast_combo_mult: "连击：+MULT",
      toast_upgrade: "升级：{0}",
      toast_reroll: "重掷",
      toast_skip: "跳过",
      toast_shield_saved: "护盾帮你挡了一次 KO",
      name_min: "名字至少 2 个字符",
      combo_hint: "完成序列来提升倍率。",
      stats_reason: "原因",
      stats_level: "等级",
      stats_time: "时间",
      stats_streak: "连胜",
      stats_mult: "倍率",
      cell_coin: "金币",
      cell_gem: "宝石",
      cell_bonus: "奖励",
      opt_language: "语言",
      lang_auto: "自动",
      up_choose: "选择一个升级",
      up_level_title: "等级 {0}",
      rarity_common: "普通",
      rarity_rare: "稀有",
      rarity_epic: "史诗",
      rarity_legendary: "传说",
      new_profile: "创建新账号…",
      confirm_clear_local: "清除本地数据？（账号、设置、记录）",
      tag_defense: "防御",
      tag_qol: "体验",
      tag_points: "分数",
      tag_mobility: "机动",
      tag_upgrades: "升级",
      tag_combo: "连击",
      up_shield_name: "护盾",
      up_shield_desc: "抵挡 1 次 KO（消耗）。",
      up_mag1_name: "磁铁 I",
      up_mag1_desc: "吸引附近奖励（半径 1）。",
      up_mag2_name: "磁铁 II",
      up_mag2_desc: "强化磁铁（半径 2）。",
      up_mag3_name: "磁铁 III",
      up_mag3_desc: "半径 3（最大）。",
      up_boost_name: "得分 +",
      up_boost_desc: "更多分数（+8%）。",
      up_trap_name: "陷阱抗性",
      up_trap_desc: "减少陷阱惩罚。",
      up_zone_name: "区域 +",
      up_zone_desc: "移动区域更高（+1 行）。",
      up_coin_name: "金币 +",
      up_coin_desc: "金币更值钱（+2）。",
      up_gem_name: "宝石 +",
      up_gem_desc: "宝石更值钱（+6）。",
      up_bonus_name: "奖励 +",
      up_bonus_desc: "奖励更值钱（+10）。",
      up_reroll_name: "重掷 +",
      up_reroll_desc: "获得 1 次额外重掷。",
      up_mult_name: "倍率 +",
      up_mult_desc: "提高基础倍率（+0.10）。",
    },

    "zh-hant": {
      langName: "中文（繁體）",
      defaultPlayer: "玩家",
      app_ready: "就緒",
      app_loading: "啟動中…",
      app_pwa: "PWA…",
      audio_ok: "音訊 OK",
      update_apply_end: "更新已就緒：將在本局結束後套用。",
      update_available: "有可用更新。",
      update_apply_end_short: "本局結束後套用。",
      pill_update: "更新",
      toast_trap: "陷阱",
      toast_combo_mult: "連擊：+MULT",
      toast_upgrade: "升級：{0}",
      toast_reroll: "重擲",
      toast_skip: "跳過",
      toast_shield_saved: "護盾幫你擋了一次 KO",
      name_min: "名字至少 2 個字元",
      combo_hint: "完成序列來提升倍率。",
      stats_reason: "原因",
      stats_level: "等級",
      stats_time: "時間",
      stats_streak: "連勝",
      stats_mult: "倍率",
      cell_coin: "金幣",
      cell_gem: "寶石",
      cell_bonus: "獎勵",
      opt_language: "語言",
      lang_auto: "自動",
      up_choose: "選擇一個升級",
      up_level_title: "等級 {0}",
      rarity_common: "普通",
      rarity_rare: "稀有",
      rarity_epic: "史詩",
      rarity_legendary: "傳說",
      new_profile: "建立新帳號…",
      confirm_clear_local: "清除本機資料？（帳號、設定、紀錄）",
      tag_defense: "防禦",
      tag_qol: "體驗",
      tag_points: "分數",
      tag_mobility: "機動",
      tag_upgrades: "升級",
      tag_combo: "連擊",
      up_shield_name: "護盾",
      up_shield_desc: "抵擋 1 次 KO（消耗）。",
      up_mag1_name: "磁鐵 I",
      up_mag1_desc: "吸引附近獎勵（半徑 1）。",
      up_mag2_name: "磁鐵 II",
      up_mag2_desc: "強化磁鐵（半徑 2）。",
      up_mag3_name: "磁鐵 III",
      up_mag3_desc: "半徑 3（最大）。",
      up_boost_name: "得分 +",
      up_boost_desc: "更多分數（+8%）。",
      up_trap_name: "陷阱抗性",
      up_trap_desc: "減少陷阱懲罰。",
      up_zone_name: "區域 +",
      up_zone_desc: "移動區域更高（+1 行）。",
      up_coin_name: "金幣 +",
      up_coin_desc: "金幣更值錢（+2）。",
      up_gem_name: "寶石 +",
      up_gem_desc: "寶石更值錢（+6）。",
      up_bonus_name: "獎勵 +",
      up_bonus_desc: "獎勵更值錢（+10）。",
      up_reroll_name: "重擲 +",
      up_reroll_desc: "獲得 1 次額外重擲。",
      up_mult_name: "倍率 +",
      up_mult_desc: "提高基礎倍率（+0.10）。",
    },

    ja: {
      langName: "日本語",
      defaultPlayer: "プレイヤー",
      app_ready: "準備完了",
      app_loading: "起動中…",
      app_pwa: "PWA…",
      audio_ok: "オーディオ OK",
      update_apply_end: "アップデート準備完了：ラン終了後に適用されます。",
      update_available: "アップデートがあります。",
      update_apply_end_short: "終了後に適用。",
      pill_update: "更新",
      toast_trap: "トラップ",
      toast_combo_mult: "コンボ：+MULT",
      toast_upgrade: "強化：{0}",
      toast_reroll: "リロール",
      toast_skip: "スキップ",
      toast_shield_saved: "シールドが KO を防いだ",
      name_min: "名前は2文字以上です",
      combo_hint: "シーケンスを完成させて倍率を上げよう。",
      stats_reason: "理由",
      stats_level: "レベル",
      stats_time: "時間",
      stats_streak: "連続",
      stats_mult: "倍率",
      cell_coin: "コイン",
      cell_gem: "ジェム",
      cell_bonus: "ボーナス",
      opt_language: "言語",
      lang_auto: "自動",
      up_choose: "アップグレードを選択",
      up_level_title: "レベル {0}",
      rarity_common: "コモン",
      rarity_rare: "レア",
      rarity_epic: "エピック",
      rarity_legendary: "レジェンド",
      new_profile: "新規作成…",
      confirm_clear_local: "ローカルデータを消去しますか？（プロフィール/設定/記録）",
      tag_defense: "防御",
      tag_qol: "快適性",
      tag_points: "得点",
      tag_mobility: "機動",
      tag_upgrades: "強化",
      tag_combo: "コンボ",
      up_shield_name: "シールド",
      up_shield_desc: "KOを1回防ぐ（消費）。",
      up_mag1_name: "マグネット I",
      up_mag1_desc: "近くの報酬を引き寄せる（半径1）。",
      up_mag2_name: "マグネット II",
      up_mag2_desc: "強化マグネット（半径2）。",
      up_mag3_name: "マグネット III",
      up_mag3_desc: "半径3（最大）。",
      up_boost_name: "スコア +",
      up_boost_desc: "得点アップ（+8%）。",
      up_trap_name: "トラップ耐性",
      up_trap_desc: "トラップのペナルティを軽減。",
      up_zone_name: "ゾーン +",
      up_zone_desc: "移動ゾーンが+1行。",
      up_coin_name: "コイン +",
      up_coin_desc: "コイン価値アップ（+2）。",
      up_gem_name: "ジェム +",
      up_gem_desc: "ジェム価値アップ（+6）。",
      up_bonus_name: "ボーナス +",
      up_bonus_desc: "ボーナス価値アップ（+10）。",
      up_reroll_name: "リロール +",
      up_reroll_desc: "リロールを1回追加。",
      up_mult_name: "倍率 +",
      up_mult_desc: "基礎倍率を上げる（+0.10）。",
    },

    ko: {
      langName: "한국어",
      defaultPlayer: "플레이어",
      app_ready: "준비됨",
      app_loading: "시작 중…",
      app_pwa: "PWA…",
      audio_ok: "오디오 OK",
      update_apply_end: "업데이트 준비 완료: 이번 런이 끝나면 적용됩니다.",
      update_available: "업데이트가 있습니다.",
      update_apply_end_short: "끝나면 적용.",
      pill_update: "업데이트",
      toast_trap: "함정",
      toast_combo_mult: "콤보: +MULT",
      toast_upgrade: "업그레이드: {0}",
      toast_reroll: "리롤",
      toast_skip: "건너뛰기",
      toast_shield_saved: "방패가 KO를 막아줬어요",
      name_min: "이름은 최소 2글자",
      combo_hint: "시퀀스를 완성해 배수를 올리세요.",
      stats_reason: "이유",
      stats_level: "레벨",
      stats_time: "시간",
      stats_streak: "연속",
      stats_mult: "배수",
      cell_coin: "코인",
      cell_gem: "젬",
      cell_bonus: "보너스",
      opt_language: "언어",
      lang_auto: "자동",
      up_choose: "업그레이드를 선택하세요",
      up_level_title: "레벨 {0}",
      rarity_common: "일반",
      rarity_rare: "희귀",
      rarity_epic: "에픽",
      rarity_legendary: "전설",
      new_profile: "새로 만들기…",
      confirm_clear_local: "로컬 데이터를 삭제할까요? (프로필/설정/기록)",
      tag_defense: "방어",
      tag_qol: "편의",
      tag_points: "점수",
      tag_mobility: "기동",
      tag_upgrades: "업그레이드",
      tag_combo: "콤보",
      up_shield_name: "방패",
      up_shield_desc: "KO 1회를 막습니다(소모).",
      up_mag1_name: "자석 I",
      up_mag1_desc: "근처 보상을 끌어당김(반경 1).",
      up_mag2_name: "자석 II",
      up_mag2_desc: "강화 자석(반경 2).",
      up_mag3_name: "자석 III",
      up_mag3_desc: "반경 3(최대).",
      up_boost_name: "점수 +",
      up_boost_desc: "점수 증가(+8%).",
      up_trap_name: "함정 저항",
      up_trap_desc: "함정 페널티 감소.",
      up_zone_name: "존 +",
      up_zone_desc: "이동 존 높이 +1행.",
      up_coin_name: "코인 +",
      up_coin_desc: "코인 가치 증가(+2).",
      up_gem_name: "젬 +",
      up_gem_desc: "젬 가치 증가(+6).",
      up_bonus_name: "보너스 +",
      up_bonus_desc: "보너스 가치 증가(+10).",
      up_reroll_name: "리롤 +",
      up_reroll_desc: "추가 리롤 1회.",
      up_mult_name: "배수 +",
      up_mult_desc: "기본 배수 증가(+0.10).",
    },

    ru: {
      langName: "Русский",
      defaultPlayer: "Игрок",
      app_ready: "Готово",
      app_loading: "Запуск…",
      app_pwa: "PWA…",
      audio_ok: "Аудио OK",
      update_apply_end: "Обновление готово: применится после забега.",
      update_available: "Доступно обновление.",
      update_apply_end_short: "После забега.",
      pill_update: "Обновить",
      toast_trap: "Ловушка",
      toast_combo_mult: "Комбо: +MULT",
      toast_upgrade: "Улучшение: {0}",
      toast_reroll: "Реролл",
      toast_skip: "Пропустить",
      toast_shield_saved: "Щит спас от KO",
      name_min: "Имя: минимум 2 символа",
      combo_hint: "Собери последовательность, чтобы повысить множитель.",
      stats_reason: "Причина",
      stats_level: "Уровень",
      stats_time: "Время",
      stats_streak: "Серия",
      stats_mult: "Множ.",
      cell_coin: "Монета",
      cell_gem: "Гем",
      cell_bonus: "Бонус",
      opt_language: "Язык",
      lang_auto: "Авто",
      up_choose: "Выбери улучшение",
      up_level_title: "Уровень {0}",
      rarity_common: "Обычное",
      rarity_rare: "Редкое",
      rarity_epic: "Эпическое",
      rarity_legendary: "Легендарное",
      new_profile: "Создать новый…",
      confirm_clear_local: "Очистить локальные данные? (Профили, настройки, забеги)",
      tag_defense: "Защита",
      tag_qol: "QoL",
      tag_points: "Очки",
      tag_mobility: "Мобильность",
      tag_upgrades: "Улучшения",
      tag_combo: "Комбо",
      up_shield_name: "Щит",
      up_shield_desc: "Блокирует 1 KO (тратится).",
      up_mag1_name: "Магнит I",
      up_mag1_desc: "Притягивает награды (радиус 1).",
      up_mag2_name: "Магнит II",
      up_mag2_desc: "Усиленный магнит (радиус 2).",
      up_mag3_name: "Магнит III",
      up_mag3_desc: "Радиус 3 (макс).",
      up_boost_name: "Очки +",
      up_boost_desc: "Больше очков (+8%).",
      up_trap_name: "Сопротивление ловушкам",
      up_trap_desc: "Снижает штраф ловушек.",
      up_zone_name: "Зона +",
      up_zone_desc: "Зона движения выше (+1 ряд).",
      up_coin_name: "Монета +",
      up_coin_desc: "Монета дороже (+2).",
      up_gem_name: "Гем +",
      up_gem_desc: "Гем дороже (+6).",
      up_bonus_name: "Бонус +",
      up_bonus_desc: "Бонус дороже (+10).",
      up_reroll_name: "Реролл +",
      up_reroll_desc: "Получаешь +1 реролл.",
      up_mult_name: "Множ. +",
      up_mult_desc: "Повышает базовый множитель (+0.10).",
    },

    ar: {
      langName: "العربية",
      defaultPlayer: "لاعب",
      app_ready: "جاهز",
      app_loading: "جارٍ البدء…",
      app_pwa: "PWA…",
      audio_ok: "الصوت OK",
      update_apply_end: "التحديث جاهز: سيُطبَّق بعد الجولة.",
      update_available: "يوجد تحديث متاح.",
      update_apply_end_short: "بعد الجولة.",
      pill_update: "تحديث",
      toast_trap: "فخ",
      toast_combo_mult: "كومبو: +MULT",
      toast_upgrade: "ترقية: {0}",
      toast_reroll: "إعادة رمي",
      toast_skip: "تخطي",
      toast_shield_saved: "الدرع أنقذك من KO",
      name_min: "الاسم: حرفان على الأقل",
      combo_hint: "أكمل التسلسل لزيادة المضاعف.",
      stats_reason: "السبب",
      stats_level: "المستوى",
      stats_time: "الوقت",
      stats_streak: "سلسلة",
      stats_mult: "مضاعف",
      cell_coin: "عملة",
      cell_gem: "جوهرة",
      cell_bonus: "بونص",
      opt_language: "اللغة",
      lang_auto: "تلقائي",
      up_choose: "اختر ترقية",
      up_level_title: "المستوى {0}",
      rarity_common: "عادي",
      rarity_rare: "نادر",
      rarity_epic: "ملحمي",
      rarity_legendary: "أسطوري",
      new_profile: "إنشاء جديد…",
      confirm_clear_local: "مسح البيانات المحلية؟ (ملفات/إعدادات/جولات)",
      tag_defense: "دفاع",
      tag_qol: "راحة",
      tag_points: "نقاط",
      tag_mobility: "حركة",
      tag_upgrades: "ترقيات",
      tag_combo: "كومبو",
      up_shield_name: "درع",
      up_shield_desc: "يمنع KO واحد (يُستهلك).",
      up_mag1_name: "مغناطيس I",
      up_mag1_desc: "يجذب المكافآت القريبة (مدى 1).",
      up_mag2_name: "مغناطيس II",
      up_mag2_desc: "مغناطيس أقوى (مدى 2).",
      up_mag3_name: "مغناطيس III",
      up_mag3_desc: "مدى 3 (الحد الأقصى).",
      up_boost_name: "نقاط +",
      up_boost_desc: "نقاط أكثر (+8%).",
      up_trap_name: "مقاومة الفخاخ",
      up_trap_desc: "يقلل عقوبة الفخاخ.",
      up_zone_name: "منطقة +",
      up_zone_desc: "منطقة حركة أعلى (+1 صف).",
      up_coin_name: "عملة +",
      up_coin_desc: "العملة تساوي أكثر (+2).",
      up_gem_name: "جوهرة +",
      up_gem_desc: "الجوهرة تساوي أكثر (+6).",
      up_bonus_name: "بونص +",
      up_bonus_desc: "البونص يساوي أكثر (+10).",
      up_reroll_name: "إعادة رمي +",
      up_reroll_desc: "تحصل على إعادة رمي إضافية واحدة.",
      up_mult_name: "مضاعف +",
      up_mult_desc: "يزيد المضاعف الأساسي (+0.10).",
    },

    // ───────────────────────── EXTRA (“y demás”) ─────────────────────────

    tr: {
      langName: "Türkçe",
      defaultPlayer: "Oyuncu",
      app_ready: "Hazır",
      app_loading: "Başlatılıyor…",
      app_pwa: "PWA…",
      audio_ok: "Ses OK",
      update_apply_end: "Güncelleme hazır: koşu bitince uygulanacak.",
      update_available: "Güncelleme var.",
      update_apply_end_short: "Koşu bitince.",
      pill_update: "Güncelle",
      toast_trap: "Tuzak",
      toast_combo_mult: "Kombo: +MULT",
      toast_upgrade: "Yükseltme: {0}",
      toast_reroll: "Reroll",
      toast_skip: "Geç",
      toast_shield_saved: "Kalkan bir KO’yu engelledi",
      name_min: "İsim en az 2 karakter",
      combo_hint: "Çarpanı artırmak için diziyi tamamla.",
      stats_reason: "Sebep",
      stats_level: "Seviye",
      stats_time: "Süre",
      stats_streak: "Seri",
      stats_mult: "Çarpan",
      cell_coin: "Coin",
      cell_gem: "Gem",
      cell_bonus: "Bonus",
      opt_language: "Dil",
      lang_auto: "Oto",
      up_choose: "Bir yükseltme seç",
      up_level_title: "Seviye {0}",
      rarity_common: "Yaygın",
      rarity_rare: "Nadir",
      rarity_epic: "Epik",
      rarity_legendary: "Efsane",
      new_profile: "Yeni oluştur…",
      confirm_clear_local: "Yerel veriler silinsin mi? (Profil/ayarlar/runs)",
      tag_defense: "Savunma",
      tag_qol: "Konfor",
      tag_points: "Puan",
      tag_mobility: "Hareket",
      tag_upgrades: "Yükseltmeler",
      tag_combo: "Kombo",
      up_shield_name: "Kalkan",
      up_shield_desc: "1 KO engeller (tüketilir).",
      up_mag1_name: "Mıknatıs I",
      up_mag1_desc: "Yakın ödülleri çeker (menzil 1).",
      up_mag2_name: "Mıknatıs II",
      up_mag2_desc: "Gelişmiş mıknatıs (menzil 2).",
      up_mag3_name: "Mıknatıs III",
      up_mag3_desc: "Menzil 3 (maks).",
      up_boost_name: "Skor +",
      up_boost_desc: "Daha fazla puan (+8%).",
      up_trap_name: "Tuzak direnci",
      up_trap_desc: "Tuzak cezasını azaltır.",
      up_zone_name: "Bölge +",
      up_zone_desc: "Hareket bölgesi +1 satır.",
      up_coin_name: "Coin +",
      up_coin_desc: "Coin daha değerli (+2).",
      up_gem_name: "Gem +",
      up_gem_desc: "Gem daha değerli (+6).",
      up_bonus_name: "Bonus +",
      up_bonus_desc: "Bonus daha değerli (+10).",
      up_reroll_name: "Reroll +",
      up_reroll_desc: "1 ekstra reroll kazan.",
      up_mult_name: "Çarpan +",
      up_mult_desc: "Temel çarpanı artırır (+0.10).",
    },

    pl: {
      langName: "Polski",
      defaultPlayer: "Gracz",
      app_ready: "Gotowe",
      app_loading: "Uruchamianie…",
      app_pwa: "PWA…",
      audio_ok: "Audio OK",
      update_apply_end: "Aktualizacja gotowa: zostanie zastosowana po rundzie.",
      update_available: "Dostępna aktualizacja.",
      update_apply_end_short: "Po rundzie.",
      pill_update: "Aktualizuj",
      toast_trap: "Pułapka",
      toast_combo_mult: "Combo: +MULT",
      toast_upgrade: "Ulepszenie: {0}",
      toast_reroll: "Reroll",
      toast_skip: "Pomiń",
      toast_shield_saved: "Tarcza uratowała przed KO",
      name_min: "Nazwa: min. 2 znaki",
      combo_hint: "Ukończ sekwencję, aby zwiększyć mnożnik.",
      stats_reason: "Powód",
      stats_level: "Poziom",
      stats_time: "Czas",
      stats_streak: "Seria",
      stats_mult: "Mnoż.",
      cell_coin: "Moneta",
      cell_gem: "Klejnot",
      cell_bonus: "Bonus",
      opt_language: "Język",
      lang_auto: "Auto",
      up_choose: "Wybierz ulepszenie",
      up_level_title: "Poziom {0}",
      rarity_common: "Zwykłe",
      rarity_rare: "Rzadkie",
      rarity_epic: "Epickie",
      rarity_legendary: "Legendarne",
      new_profile: "Utwórz nowe…",
      confirm_clear_local: "Wyczyścić dane lokalne? (Profile/ustawienia/gry)",
      tag_defense: "Obrona",
      tag_qol: "QoL",
      tag_points: "Punkty",
      tag_mobility: "Mobilność",
      tag_upgrades: "Ulepszenia",
      tag_combo: "Combo",
      up_shield_name: "Tarcza",
      up_shield_desc: "Blokuje 1 KO (zużywa się).",
      up_mag1_name: "Magnes I",
      up_mag1_desc: "Przyciąga nagrody (promień 1).",
      up_mag2_name: "Magnes II",
      up_mag2_desc: "Lepszy magnes (promień 2).",
      up_mag3_name: "Magnes III",
      up_mag3_desc: "Promień 3 (max).",
      up_boost_name: "Wynik +",
      up_boost_desc: "Więcej punktów (+8%).",
      up_trap_name: "Odporność na pułapki",
      up_trap_desc: "Zmniejsza karę za pułapki.",
      up_zone_name: "Strefa +",
      up_zone_desc: "Wyższa strefa ruchu (+1 rząd).",
      up_coin_name: "Moneta +",
      up_coin_desc: "Moneta warta więcej (+2).",
      up_gem_name: "Klejnot +",
      up_gem_desc: "Klejnot warty więcej (+6).",
      up_bonus_name: "Bonus +",
      up_bonus_desc: "Bonus warty więcej (+10).",
      up_reroll_name: "Reroll +",
      up_reroll_desc: "Dodatkowy 1 reroll.",
      up_mult_name: "Mnoż. +",
      up_mult_desc: "Zwiększa bazowy mnożnik (+0.10).",
    },

    nl: {
      langName: "Nederlands",
      defaultPlayer: "Speler",
      app_ready: "Klaar",
      app_loading: "Starten…",
      app_pwa: "PWA…",
      audio_ok: "Audio OK",
      update_apply_end: "Update klaar: wordt toegepast na de run.",
      update_available: "Update beschikbaar.",
      update_apply_end_short: "Na de run.",
      pill_update: "Updaten",
      toast_trap: "Val",
      toast_combo_mult: "Combo: +MULT",
      toast_upgrade: "Upgrade: {0}",
      toast_reroll: "Reroll",
      toast_skip: "Overslaan",
      toast_shield_saved: "Schild redde je van een KO",
      name_min: "Naam: minimaal 2 tekens",
      combo_hint: "Voltooi de reeks om de multiplier te verhogen.",
      stats_reason: "Reden",
      stats_level: "Level",
      stats_time: "Tijd",
      stats_streak: "Reeks",
      stats_mult: "Mult",
      cell_coin: "Coin",
      cell_gem: "Gem",
      cell_bonus: "Bonus",
      opt_language: "Taal",
      lang_auto: "Auto",
      up_choose: "Kies een upgrade",
      up_level_title: "Level {0}",
      rarity_common: "Gewoon",
      rarity_rare: "Zeldzaam",
      rarity_epic: "Episch",
      rarity_legendary: "Legendarisch",
      new_profile: "Nieuw maken…",
      confirm_clear_local: "Lokale data wissen? (Profielen/instellingen/runs)",
      tag_defense: "Verdediging",
      tag_qol: "QoL",
      tag_points: "Punten",
      tag_mobility: "Mobiliteit",
      tag_upgrades: "Upgrades",
      tag_combo: "Combo",
      up_shield_name: "Schild",
      up_shield_desc: "Blokkeert 1 KO (verbruikt).",
      up_mag1_name: "Magneet I",
      up_mag1_desc: "Trekt beloningen aan (radius 1).",
      up_mag2_name: "Magneet II",
      up_mag2_desc: "Betere magneet (radius 2).",
      up_mag3_name: "Magneet III",
      up_mag3_desc: "Radius 3 (max).",
      up_boost_name: "Score +",
      up_boost_desc: "Meer punten (+8%).",
      up_trap_name: "Valbestendigheid",
      up_trap_desc: "Vermindert val-penalty.",
      up_zone_name: "Zone +",
      up_zone_desc: "Hogere bewegingszone (+1 rij).",
      up_coin_name: "Coin +",
      up_coin_desc: "Coin meer waard (+2).",
      up_gem_name: "Gem +",
      up_gem_desc: "Gem meer waard (+6).",
      up_bonus_name: "Bonus +",
      up_bonus_desc: "Bonus meer waard (+10).",
      up_reroll_name: "Reroll +",
      up_reroll_desc: "Krijg 1 extra reroll.",
      up_mult_name: "Mult +",
      up_mult_desc: "Verhoogt basismultiplier (+0.10).",
    },
  };

  const supported = ["auto", ...Object.keys(dict)];
  let current = "es";

  function detectBrowser() {
    const nav = (navigator.languages && navigator.languages[0]) || navigator.language || "es";
    const n = normalize(nav);
    return dict[n] ? n : "en";
  }

  function setDocLangAndDir(code) {
    try { document.documentElement.lang = code; } catch {}
    try { document.documentElement.dir = RTL_LANGS.has(code) ? "rtl" : "ltr"; } catch {}
  }

  function setLang(raw) {
    const n = normalize(raw);
    if (n === "auto") current = detectBrowser();
    else current = dict[n] ? n : "en";
    setDocLangAndDir(current);
  }

  function getLang() { return current; }

  function fmt(str, args) {
    return String(str).replace(/\{(\d+)\}/g, (_, i) =>
      (args && args[+i] != null) ? String(args[+i]) : ""
    );
  }

  function t(key, ...args) {
    const base = dict[current] || dict.en || dict.es;
    const fallback = dict.en || dict.es || {};
    const val =
      (base && base[key] != null) ? base[key] :
      (fallback[key] != null ? fallback[key] : (dict.es?.[key] ?? key));

    return args.length ? fmt(val, args) : String(val);
  }

  function languageOptions() {
    const order = [
      "auto",
      "es", "en",
      "zh", "zh-hant",
      "ja", "ko",
      "ru", "ar",
      "fr", "de", "it", "pt", "ca",
      "tr", "pl", "nl",
    ];

    const out = [];
    for (const code of order) {
      if (!supported.includes(code)) continue;
      if (code === "auto") out.push({ code, label: (dict[current]?.lang_auto || dict.en.lang_auto || "Auto") });
      else out.push({ code, label: dict[code]?.langName || code.toUpperCase() });
    }

    // append any non-listed supported (future-proof)
    for (const code of supported) {
      if (order.includes(code) || code === "auto") continue;
      out.push({ code, label: dict[code]?.langName || code.toUpperCase() });
    }
    return out;
  }

  function applyDataAttrs(root = document) {
    try {
      root.querySelectorAll?.("[data-i18n]")?.forEach((el) => {
        const k = el.getAttribute("data-i18n");
        if (k) el.textContent = t(k);
      });
      root.querySelectorAll?.("[data-i18n-title]")?.forEach((el) => {
        const k = el.getAttribute("data-i18n-title");
        if (k) el.title = t(k);
      });
      root.querySelectorAll?.("[data-i18n-ph]")?.forEach((el) => {
        const k = el.getAttribute("data-i18n-ph");
        if (k) el.placeholder = t(k);
      });
    } catch {}
  }

  // init doc lang/dir with default
  setDocLangAndDir(current);

  window.I18n = Object.freeze({
    setLang,
    getLang,
    t,
    languageOptions,
    applyDataAttrs,
  });
})();
