/* localization.js — Grid Rogue v0.1.7
   I18N separado (window.I18n)
*/
(() => {
  "use strict";

  const normalize = (raw) => {
    const s = String(raw || "").toLowerCase().trim();
    if (!s || s === "auto") return "auto";
    const base = s.split("-")[0];
    if (base === "pt") return "pt";
    if (base === "ca") return "ca";
    return base;
  };

  const dict = {
    es: {
      langName: "Español",
      defaultPlayer: "Jugador",
      app_ready: "Listo",
      app_loading: "Iniciando…",
      app_pwa: "PWA…",
      audio_ok: "Audio OK",
      update_apply_end: "Update listo: se aplicará al terminar.",
      update_available: "Actualización disponible.",
      update_apply_end_short: "Se aplicará al terminar.",
      pill_update: "Actualizar",
      toast_trap: "Trampa",
      toast_combo_mult: "Combo: +MULT",
      toast_upgrade: "Mejora: {0}",
      toast_reroll: "Reroll",
      toast_skip: "Saltar",
      toast_shield_saved: "El escudo salvó un KO",
      name_min: "Nombre mínimo 2 letras",
      combo_hint: "Completa la secuencia para subir multiplicador.",
      stats_reason: "Motivo",
      stats_level: "Nivel",
      stats_time: "Tiempo",
      stats_streak: "Racha",
      stats_mult: "Mult",
      cell_coin: "Coin",
      cell_gem: "Gem",
      cell_bonus: "Bonus",
      opt_language: "Idioma",
      lang_auto: "Auto",
      up_choose: "Elige una mejora",
      up_level_title: "Nivel {0}",
      rarity_common: "Común",
      rarity_rare: "Rara",
      rarity_epic: "Épica",
      rarity_legendary: "Legendaria",
      new_profile: "Crear nuevo…",
      confirm_clear_local: "¿Borrar datos locales? (Perfiles, ajustes, runs)",
      tag_defense: "Defensa",
      tag_qol: "QoL",
      tag_points: "Puntos",
      tag_mobility: "Movilidad",
      tag_upgrades: "Upgrades",
      tag_combo: "Combo",
      up_shield_name: "Escudo",
      up_shield_desc: "Bloquea 1 KO (se consume).",
      up_mag1_name: "Imán I",
      up_mag1_desc: "Atrae premios cercanos (radio 1).",
      up_mag2_name: "Imán II",
      up_mag2_desc: "Imán mejorado (radio 2).",
      up_mag3_name: "Imán III",
      up_mag3_desc: "Radio 3 (máximo).",
      up_boost_name: "Puntos +",
      up_boost_desc: "Más puntos (+8%).",
      up_trap_name: "Resistencia a trampas",
      up_trap_desc: "Reduce penalización de trampas.",
      up_zone_name: "Zona +",
      up_zone_desc: "Zona de movimiento más alta (+1 fila).",
      up_coin_name: "Coin +",
      up_coin_desc: "Coin vale más (+2).",
      up_gem_name: "Gem +",
      up_gem_desc: "Gem vale más (+6).",
      up_bonus_name: "Bonus +",
      up_bonus_desc: "Bonus vale más (+10).",
      up_reroll_name: "Reroll +",
      up_reroll_desc: "Ganas 1 reroll extra.",
      up_mult_name: "Mult +",
      up_mult_desc: "Sube multiplicador base (+0.10).",
    },
    en: {
      langName: "English",
      defaultPlayer: "Player",
      app_ready: "Ready",
      app_loading: "Starting…",
      app_pwa: "PWA…",
      audio_ok: "Audio OK",
      update_apply_end: "Update ready: it will apply after the run.",
      update_available: "Update available.",
      update_apply_end_short: "It will apply after the run.",
      pill_update: "Update",
      toast_trap: "Trap",
      toast_combo_mult: "Combo: +MULT",
      toast_upgrade: "Upgrade: {0}",
      toast_reroll: "Reroll",
      toast_skip: "Skip",
      toast_shield_saved: "Shield saved you from a KO",
      name_min: "Name must be at least 2 characters",
      combo_hint: "Complete the sequence to increase multiplier.",
      stats_reason: "Reason",
      stats_level: "Level",
      stats_time: "Time",
      stats_streak: "Streak",
      stats_mult: "Mult",
      cell_coin: "Coin",
      cell_gem: "Gem",
      cell_bonus: "Bonus",
      opt_language: "Language",
      lang_auto: "Auto",
      up_choose: "Choose an upgrade",
      up_level_title: "Level {0}",
      rarity_common: "Common",
      rarity_rare: "Rare",
      rarity_epic: "Epic",
      rarity_legendary: "Legendary",
      new_profile: "Create new…",
      confirm_clear_local: "Clear local data? (Profiles, settings, runs)",
      tag_defense: "Defense",
      tag_qol: "QoL",
      tag_points: "Points",
      tag_mobility: "Mobility",
      tag_upgrades: "Upgrades",
      tag_combo: "Combo",
      up_shield_name: "Shield",
      up_shield_desc: "Blocks 1 KO (consumed).",
      up_mag1_name: "Magnet I",
      up_mag1_desc: "Pulls nearby rewards (radius 1).",
      up_mag2_name: "Magnet II",
      up_mag2_desc: "Improved magnet (radius 2).",
      up_mag3_name: "Magnet III",
      up_mag3_desc: "Radius 3 (max).",
      up_boost_name: "Score +",
      up_boost_desc: "More points (+8%).",
      up_trap_name: "Trap resistance",
      up_trap_desc: "Reduces trap penalty.",
      up_zone_name: "Zone +",
      up_zone_desc: "Taller movement zone (+1 row).",
      up_coin_name: "Coin +",
      up_coin_desc: "Coin worth more (+2).",
      up_gem_name: "Gem +",
      up_gem_desc: "Gem worth more (+6).",
      up_bonus_name: "Bonus +",
      up_bonus_desc: "Bonus worth more (+10).",
      up_reroll_name: "Reroll +",
      up_reroll_desc: "Gain 1 extra reroll.",
      up_mult_name: "Mult +",
      up_mult_desc: "Increase base multiplier (+0.10).",
    },
    fr: {
      langName: "Français",
      defaultPlayer: "Joueur",
      app_ready: "Prêt",
      app_loading: "Démarrage…",
      app_pwa: "PWA…",
      audio_ok: "Audio OK",
      update_apply_end: "MAJ prête : elle s’appliquera après la partie.",
      update_available: "Mise à jour disponible.",
      update_apply_end_short: "Après la partie.",
      pill_update: "Mettre à jour",
      toast_trap: "Piège",
      toast_combo_mult: "Combo : +MULT",
      toast_upgrade: "Amélioration : {0}",
      toast_reroll: "Relance",
      toast_skip: "Passer",
      toast_shield_saved: "Bouclier : KO évité",
      name_min: "Nom : minimum 2 caractères",
      combo_hint: "Complète la séquence pour augmenter le multiplicateur.",
      stats_reason: "Raison",
      stats_level: "Niveau",
      stats_time: "Temps",
      stats_streak: "Série",
      stats_mult: "Mult",
      cell_coin: "Pièce",
      cell_gem: "Gemme",
      cell_bonus: "Bonus",
      opt_language: "Langue",
      lang_auto: "Auto",
      up_choose: "Choisis une amélioration",
      up_level_title: "Niveau {0}",
      rarity_common: "Commune",
      rarity_rare: "Rare",
      rarity_epic: "Épique",
      rarity_legendary: "Légendaire",
      new_profile: "Créer nouveau…",
      confirm_clear_local: "Effacer les données locales ? (Profils, réglages, runs)",
      tag_defense: "Défense",
      tag_qol: "QoL",
      tag_points: "Points",
      tag_mobility: "Mobilité",
      tag_upgrades: "Amélios",
      tag_combo: "Combo",
      up_shield_name: "Bouclier",
      up_shield_desc: "Bloque 1 KO (consommé).",
      up_mag1_name: "Aimant I",
      up_mag1_desc: "Attire les récompenses (rayon 1).",
      up_mag2_name: "Aimant II",
      up_mag2_desc: "Aimant amélioré (rayon 2).",
      up_mag3_name: "Aimant III",
      up_mag3_desc: "Rayon 3 (max).",
      up_boost_name: "Score +",
      up_boost_desc: "Plus de points (+8%).",
      up_trap_name: "Résistance pièges",
      up_trap_desc: "Réduit la pénalité des pièges.",
      up_zone_name: "Zone +",
      up_zone_desc: "Zone de mouvement plus haute (+1 ligne).",
      up_coin_name: "Pièce +",
      up_coin_desc: "Pièce vaut plus (+2).",
      up_gem_name: "Gemme +",
      up_gem_desc: "Gemme vaut plus (+6).",
      up_bonus_name: "Bonus +",
      up_bonus_desc: "Bonus vaut plus (+10).",
      up_reroll_name: "Relance +",
      up_reroll_desc: "Gagne 1 relance.",
      up_mult_name: "Mult +",
      up_mult_desc: "Augmente le mult de base (+0,10).",
    },
    de: {
      langName: "Deutsch",
      defaultPlayer: "Spieler",
      app_ready: "Bereit",
      app_loading: "Startet…",
      app_pwa: "PWA…",
      audio_ok: "Audio OK",
      update_apply_end: "Update bereit: wird nach dem Lauf angewendet.",
      update_available: "Update verfügbar.",
      update_apply_end_short: "Nach dem Lauf.",
      pill_update: "Aktualisieren",
      toast_trap: "Falle",
      toast_combo_mult: "Combo: +MULT",
      toast_upgrade: "Upgrade: {0}",
      toast_reroll: "Neu würfeln",
      toast_skip: "Überspringen",
      toast_shield_saved: "Schild hat dich vor KO gerettet",
      name_min: "Name: mindestens 2 Zeichen",
      combo_hint: "Vervollständige die Sequenz für mehr Multiplikator.",
      stats_reason: "Grund",
      stats_level: "Level",
      stats_time: "Zeit",
      stats_streak: "Serie",
      stats_mult: "Mult",
      cell_coin: "Coin",
      cell_gem: "Gem",
      cell_bonus: "Bonus",
      opt_language: "Sprache",
      lang_auto: "Auto",
      up_choose: "Wähle ein Upgrade",
      up_level_title: "Level {0}",
      rarity_common: "Gewöhnlich",
      rarity_rare: "Selten",
      rarity_epic: "Episch",
      rarity_legendary: "Legendär",
      new_profile: "Neu erstellen…",
      confirm_clear_local: "Lokale Daten löschen? (Profile, Einstellungen, Runs)",
      tag_defense: "Verteidigung",
      tag_qol: "QoL",
      tag_points: "Punkte",
      tag_mobility: "Mobilität",
      tag_upgrades: "Upgrades",
      tag_combo: "Combo",
      up_shield_name: "Schild",
      up_shield_desc: "Blockt 1 KO (verbraucht).",
      up_mag1_name: "Magnet I",
      up_mag1_desc: "Zieht Belohnungen an (Radius 1).",
      up_mag2_name: "Magnet II",
      up_mag2_desc: "Besserer Magnet (Radius 2).",
      up_mag3_name: "Magnet III",
      up_mag3_desc: "Radius 3 (Max).",
      up_boost_name: "Score +",
      up_boost_desc: "Mehr Punkte (+8%).",
      up_trap_name: "Fallenresistenz",
      up_trap_desc: "Reduziert Fallenstrafe.",
      up_zone_name: "Zone +",
      up_zone_desc: "Höhere Bewegungszone (+1 Reihe).",
      up_coin_name: "Coin +",
      up_coin_desc: "Coin ist mehr wert (+2).",
      up_gem_name: "Gem +",
      up_gem_desc: "Gem ist mehr wert (+6).",
      up_bonus_name: "Bonus +",
      up_bonus_desc: "Bonus ist mehr wert (+10).",
      up_reroll_name: "Reroll +",
      up_reroll_desc: "Erhalte 1 zusätzlichen Reroll.",
      up_mult_name: "Mult +",
      up_mult_desc: "Erhöht Basismultiplikator (+0,10).",
    },
    it: {
      langName: "Italiano",
      defaultPlayer: "Giocatore",
      app_ready: "Pronto",
      app_loading: "Avvio…",
      app_pwa: "PWA…",
      audio_ok: "Audio OK",
      update_apply_end: "Aggiornamento pronto: si applicherà dopo la run.",
      update_available: "Aggiornamento disponibile.",
      update_apply_end_short: "Dopo la run.",
      pill_update: "Aggiorna",
      toast_trap: "Trappola",
      toast_combo_mult: "Combo: +MULT",
      toast_upgrade: "Miglioria: {0}",
      toast_reroll: "Reroll",
      toast_skip: "Salta",
      toast_shield_saved: "Scudo: KO evitato",
      name_min: "Nome: minimo 2 caratteri",
      combo_hint: "Completa la sequenza per aumentare il moltiplicatore.",
      stats_reason: "Motivo",
      stats_level: "Livello",
      stats_time: "Tempo",
      stats_streak: "Serie",
      stats_mult: "Mult",
      cell_coin: "Coin",
      cell_gem: "Gem",
      cell_bonus: "Bonus",
      opt_language: "Lingua",
      lang_auto: "Auto",
      up_choose: "Scegli un upgrade",
      up_level_title: "Livello {0}",
      rarity_common: "Comune",
      rarity_rare: "Raro",
      rarity_epic: "Epico",
      rarity_legendary: "Leggendario",
      new_profile: "Crea nuovo…",
      confirm_clear_local: "Cancellare i dati locali? (Profili, impostazioni, runs)",
      tag_defense: "Difesa",
      tag_qol: "QoL",
      tag_points: "Punti",
      tag_mobility: "Mobilità",
      tag_upgrades: "Upgrade",
      tag_combo: "Combo",
      up_shield_name: "Scudo",
      up_shield_desc: "Blocca 1 KO (consumato).",
      up_mag1_name: "Magnete I",
      up_mag1_desc: "Attira ricompense (raggio 1).",
      up_mag2_name: "Magnete II",
      up_mag2_desc: "Magnete migliorato (raggio 2).",
      up_mag3_name: "Magnete III",
      up_mag3_desc: "Raggio 3 (max).",
      up_boost_name: "Punti +",
      up_boost_desc: "Più punti (+8%).",
      up_trap_name: "Resistenza trappole",
      up_trap_desc: "Riduce la penalità delle trappole.",
      up_zone_name: "Zona +",
      up_zone_desc: "Zona movimento più alta (+1 riga).",
      up_coin_name: "Coin +",
      up_coin_desc: "Coin vale di più (+2).",
      up_gem_name: "Gem +",
      up_gem_desc: "Gem vale di più (+6).",
      up_bonus_name: "Bonus +",
      up_bonus_desc: "Bonus vale di più (+10).",
      up_reroll_name: "Reroll +",
      up_reroll_desc: "Ottieni 1 reroll extra.",
      up_mult_name: "Mult +",
      up_mult_desc: "Aumenta mult base (+0,10).",
    },
    pt: {
      langName: "Português",
      defaultPlayer: "Jogador",
      app_ready: "Pronto",
      app_loading: "A iniciar…",
      app_pwa: "PWA…",
      audio_ok: "Áudio OK",
      update_apply_end: "Update pronto: aplica-se no fim da run.",
      update_available: "Atualização disponível.",
      update_apply_end_short: "No fim da run.",
      pill_update: "Atualizar",
      toast_trap: "Armadilha",
      toast_combo_mult: "Combo: +MULT",
      toast_upgrade: "Upgrade: {0}",
      toast_reroll: "Reroll",
      toast_skip: "Saltar",
      toast_shield_saved: "Escudo salvou-te de um KO",
      name_min: "Nome: mínimo 2 caracteres",
      combo_hint: "Completa a sequência para aumentar o multiplicador.",
      stats_reason: "Motivo",
      stats_level: "Nível",
      stats_time: "Tempo",
      stats_streak: "Sequência",
      stats_mult: "Mult",
      cell_coin: "Coin",
      cell_gem: "Gem",
      cell_bonus: "Bónus",
      opt_language: "Idioma",
      lang_auto: "Auto",
      up_choose: "Escolhe um upgrade",
      up_level_title: "Nível {0}",
      rarity_common: "Comum",
      rarity_rare: "Raro",
      rarity_epic: "Épico",
      rarity_legendary: "Lendário",
      new_profile: "Criar novo…",
      confirm_clear_local: "Apagar dados locais? (Perfis, definições, runs)",
      tag_defense: "Defesa",
      tag_qol: "QoL",
      tag_points: "Pontos",
      tag_mobility: "Mobilidade",
      tag_upgrades: "Upgrades",
      tag_combo: "Combo",
      up_shield_name: "Escudo",
      up_shield_desc: "Bloqueia 1 KO (consome).",
      up_mag1_name: "Íman I",
      up_mag1_desc: "Atrai prémios (raio 1).",
      up_mag2_name: "Íman II",
      up_mag2_desc: "Íman melhorado (raio 2).",
      up_mag3_name: "Íman III",
      up_mag3_desc: "Raio 3 (máx).",
      up_boost_name: "Pontos +",
      up_boost_desc: "Mais pontos (+8%).",
      up_trap_name: "Resistência a armadilhas",
      up_trap_desc: "Reduz penalização das armadilhas.",
      up_zone_name: "Zona +",
      up_zone_desc: "Zona de movimento maior (+1 linha).",
      up_coin_name: "Coin +",
      up_coin_desc: "Coin vale mais (+2).",
      up_gem_name: "Gem +",
      up_gem_desc: "Gem vale mais (+6).",
      up_bonus_name: "Bónus +",
      up_bonus_desc: "Bónus vale mais (+10).",
      up_reroll_name: "Reroll +",
      up_reroll_desc: "Ganhas 1 reroll extra.",
      up_mult_name: "Mult +",
      up_mult_desc: "Aumenta mult base (+0,10).",
    },
    ca: {
      langName: "Català",
      defaultPlayer: "Jugador",
      app_ready: "A punt",
      app_loading: "Iniciant…",
      app_pwa: "PWA…",
      audio_ok: "Àudio OK",
      update_apply_end: "Actualització llesta: s’aplicarà en acabar la run.",
      update_available: "Actualització disponible.",
      update_apply_end_short: "En acabar la run.",
      pill_update: "Actualitza",
      toast_trap: "Trampa",
      toast_combo_mult: "Combo: +MULT",
      toast_upgrade: "Millora: {0}",
      toast_reroll: "Reroll",
      toast_skip: "Saltar",
      toast_shield_saved: "L’escut t’ha salvat d’un KO",
      name_min: "Nom: mínim 2 lletres",
      combo_hint: "Completa la seqüència per pujar multiplicador.",
      stats_reason: "Motiu",
      stats_level: "Nivell",
      stats_time: "Temps",
      stats_streak: "Ratxa",
      stats_mult: "Mult",
      cell_coin: "Coin",
      cell_gem: "Gem",
      cell_bonus: "Bonus",
      opt_language: "Idioma",
      lang_auto: "Auto",
      up_choose: "Tria una millora",
      up_level_title: "Nivell {0}",
      rarity_common: "Comuna",
      rarity_rare: "Rara",
      rarity_epic: "Èpica",
      rarity_legendary: "Legendària",
      new_profile: "Crear nou…",
      confirm_clear_local: "Esborrar dades locals? (Perfils, opcions, runs)",
      tag_defense: "Defensa",
      tag_qol: "QoL",
      tag_points: "Punts",
      tag_mobility: "Mobilitat",
      tag_upgrades: "Upgrades",
      tag_combo: "Combo",
      up_shield_name: "Escut",
      up_shield_desc: "Bloqueja 1 KO (es consumeix).",
      up_mag1_name: "Imant I",
      up_mag1_desc: "Atrau premis (radi 1).",
      up_mag2_name: "Imant II",
      up_mag2_desc: "Imant millorat (radi 2).",
      up_mag3_name: "Imant III",
      up_mag3_desc: "Radi 3 (màxim).",
      up_boost_name: "Punts +",
      up_boost_desc: "Més punts (+8%).",
      up_trap_name: "Resistència trampes",
      up_trap_desc: "Redueix penalització de trampes.",
      up_zone_name: "Zona +",
      up_zone_desc: "Zona de moviment més alta (+1 fila).",
      up_coin_name: "Coin +",
      up_coin_desc: "Coin val més (+2).",
      up_gem_name: "Gem +",
      up_gem_desc: "Gem val més (+6).",
      up_bonus_name: "Bonus +",
      up_bonus_desc: "Bonus val més (+10).",
      up_reroll_name: "Reroll +",
      up_reroll_desc: "Guanyes 1 reroll extra.",
      up_mult_name: "Mult +",
      up_mult_desc: "Puja mult base (+0,10).",
    },
  };

  const supported = ["auto", ...Object.keys(dict)];
  let current = "es";

  function detectBrowser() {
    const nav = (navigator.languages && navigator.languages[0]) || navigator.language || "es";
    const n = normalize(nav);
    return dict[n] ? n : "en";
  }

  function setLang(raw) {
    const n = normalize(raw);
    if (n === "auto") current = detectBrowser();
    else current = dict[n] ? n : "en";
    try { document.documentElement.lang = current; } catch {}
  }

  function getLang() { return current; }

  function fmt(str, args) {
    return String(str).replace(/\{(\d+)\}/g, (_, i) => (args && args[+i] != null) ? String(args[+i]) : "");
  }

  function t(key, ...args) {
    const base = dict[current] || dict.en || dict.es;
    const es = dict.es || {};
    const val = (base && base[key] != null) ? base[key] : (es[key] != null ? es[key] : key);
    return args.length ? fmt(val, args) : String(val);
  }

  function languageOptions() {
    const order = ["auto", "es", "en", "fr", "de", "it", "pt", "ca"];
    const out = [];
    for (const code of order) {
      if (!supported.includes(code)) continue;
      if (code === "auto") out.push({ code, label: (dict[current]?.lang_auto || dict.es.lang_auto || "Auto") });
      else out.push({ code, label: dict[code]?.langName || code.toUpperCase() });
    }
    for (const code of supported) {
      if (order.includes(code)) continue;
      if (code === "auto") continue;
      out.push({ code, label: dict[code]?.langName || code.toUpperCase() });
    }
    return out;
  }

  function applyDataAttrs(root = document) {
    try {
      root.querySelectorAll?.("[data-i18n]")?.forEach((el) => {
        const k = el.getAttribute("data-i18n");
        if (k) el.textContent = t(k);
      });
      root.querySelectorAll?.("[data-i18n-title]")?.forEach((el) => {
        const k = el.getAttribute("data-i18n-title");
        if (k) el.title = t(k);
      });
      root.querySelectorAll?.("[data-i18n-ph]")?.forEach((el) => {
        const k = el.getAttribute("data-i18n-ph");
        if (k) el.placeholder = t(k);
      });
    } catch {}
  }

  window.I18n = Object.freeze({ setLang, getLang, t, languageOptions, applyDataAttrs });
})();
